#!/bin/bash

mkdir /opt/mcs/
mkdir /opt/mcs/bin/
mkdir /opt/mcs/conf/

chmod +x pwr-and-control-button-monitor
chmod +x admin_pwr.py
chmod +x led-daemon
chmod +x led_listen.py
chmod +r program_config.txt

chown root pwr-and-control-button-monitor
chown root admin_pwr.py
chown root led-daemon
chown root led_listen.py
chown root program_config.txt

cp pwr-and-control-button-monitor /etc/init.d
cp admin_pwr.py /opt/mcs/bin
cp led-daemon /etc/init.d
cp led_listen.py /opt/mcs/bin
cp program_config.txt /opt/mcs/conf

update-rc.d pwr-and-control-button-monitor defaults
update-rc.d led-daemon defaults
